version: '3.8'

services:
  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    cap_add:
      - NET_RAW
    networks:
      - monitoring
    dns:
      - "8.8.8.8"
      - "1.1.1.1"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets.json:/etc/prometheus/targets.json  
      - prometheus-data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      
      # --- ใช้รหัสผ่าน Login ปกติ (ชัวร์สุดสำหรับมือถือตอนนี้) ---
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=13678
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_USERS_ALLOW_SIGN_UP=false

      # --- ปิด Google Auth และ Root URL ชั่วคราว (แก้จอขาว) ---
      # (ใส่ # ไว้ข้างหน้าเพื่อให้มันไม่ทำงาน)
      # - GF_SERVER_ROOT_URL=http://10.1.55.29.nip.io:3000
      # - GF_AUTH_GOOGLE_ENABLED=true
      # - GF_AUTH_GOOGLE_CLIENT_ID=...
      # - GF_AUTH_GOOGLE_CLIENT_SECRET=...
      
      # --- ตั้งค่า SMTP (แจ้งเตือนผ่านเมล) ---
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:465
      - GF_SMTP_USER=puripaht2016@gmail.com
      - GF_SMTP_PASSWORD=hmzc sdij odcp yalt
      - GF_SMTP_FROM_ADDRESS=puripaht2016@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alert
      - GF_SMTP_SKIP_VERIFY=false

    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    networks:
      - monitoring

  service-manager:
    build: ./manager
    container_name: service-manager
    ports:
      - "5000:5000"
    volumes:
      - ./targets.json:/data/targets.json 
    networks:
      - monitoring

volumes:
  grafana-data:
  prometheus-data:

networks:
  monitoring:
    driver: bridge