global:
  scrape_interval: 15s

scrape_configs:

# -------------------------
# HTTP (Application layer)
# -------------------------
- job_name: blackbox-http
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
        - https://reg.mfu.ac.th/backend/
        - https://lms.mfu.ac.th
      labels:
        service: reg
        layer: application
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115

# -------------------------
# TCP (Transport layer)
# -------------------------
- job_name: blackbox-tcp
  metrics_path: /probe
  params:
    module: [tcp_connect]
  static_configs:
    - targets:
        - reg.mfu.ac.th:443
        - lms.mfu.ac.th:443
      labels:
        service: reg
        layer: transport
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115

# -------------------------
# DNS (Infrastructure layer)
# -------------------------
- job_name: blackbox-dns
  metrics_path: /probe
  params:
    module: [dns]
  static_configs:
    - targets:
        - reg.mfu.ac.th
        - lms.mfu.ac.th
      labels:
        service: reg
        layer: infrastructure
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
